MONGO:
  URI-MODE: true
  NORMAL:
    HOST: 127.0.0.1
    PORT: 27017
    DATABASE: moon
    AUTHENTICATION:
      ENABLED: false
      USERNAME: ''
      PASSWORD: 'admin'
      ADMIN: "admin"
  URI:
    DATABASE: moon
    CONNECTION_STRING: mongodb://127.0.0.1:27017/Moon
