main: me.zatrex.practice.Moon
name: Moon
version: '1.0-NoDebuff' # ${git.commit.id.abbrev}
author: NoDebuff Development
depend:
  - WorldEdit
softdepend:
  - PlaceholderAPI
  - VerseCore
  - Volcano
  - Nebula
  - Apollo-Bukkit
  - AquaCore
  - PolarCord
  - Phoenix
  - PhoenixAC
  - KarhuLoader
  - PolarLoader
  - Replays
  - Citizens
