main: me.zatrex.practice.Moon
name: Practice
version: '${project.version}-${git.commit.id.abbrev}' # ${git.commit.id.abbrev}
author: Zyra Development
depend:
  - WorldEdit
softdepend:
  - PlaceholderAPI
  - VerseCore
  - Volcano
  - Nebula
  - Apollo-Bukkit
  - AquaCore
  - PolarCord
  - Phoenix
  - PhoenixAC
  - KarhuLoader
  - PolarLoader
  - Replays
  - Citizens
